### ISSUE TITLE
Opening Cultists Circle in Hideout generates error in server [Missing image]

### ISSUE THREAD

**Issue by Th3NightHawk** [sp-tarkov/server#1096]
### SPT Version

4.0

### Project Type

Server

### Expected Result

Opening Cultist Circle not to generate errors on server

### Actual Result

When opening the Cultists Circle in the hideout the below error is seen in the server console

```
[Client Request] /files/Hideout/Icon_Cultist%20Zone_Small.png
File not found: /files/Hideout/Icon_Cultist%20Zone_Small
```

### Steps To Reproduce

1. Create Dev profile
2. Launch client
3. Go to Hideout
4. Open Cultist Circle

### Server Log

[server-2025-01-20.log](https://github.com/user-attachments/files/18472852/server-2025-01-20.log)

### BepinEx Log

[LogOutput.log](https://github.com/user-attachments/files/18472858/LogOutput.log)

### Client Log

[2025.01.20_5-35-24_0.16.1.0.34568 traces.log](https://github.com/user-attachments/files/18472861/2025.01.20_5-35-24_0.16.1.0.34568.traces.log)

### Player Profile

[6776edd30001f6d8ea82fdbd.json](https://github.com/user-attachments/files/18472863/6776edd30001f6d8ea82fdbd.json)

### Screenshots

![Image](https://github.com/user-attachments/assets/7312a2de-3ea7-4822-bf80-3e2a7a18455f)

**Comment by chompDev** [comment]
Fixed with https://github.com/sp-tarkov/server/commit/1048d23f6413925aff68123eb8a26818ed221698

**Comment by Th3NightHawk** [comment]
Picked up these images missing on the Hall of Fame and Gear Rack also @chompDev:

`[Client Request] /files/Hideout/EfT_UI_Icons_DogTag.png
File not found: /files/Hideout/EfT_UI_Icons_DogTag
[Client Request] /files/Hideout/EfT_UI_Icons_SmallTrophy.png
File not found: /files/Hideout/EfT_UI_Icons_SmallTrophy
[Client Request] /files/Hideout/EfT_UI_Icons_BigTrophy.png
File not found: /files/Hideout/EfT_UI_Icons_BigTrophy`

`[Client Request] /files/Hideout/Icon_Preset-stand_Mannequin_Small.png
File not found: /files/Hideout/Icon_Preset-stand_Mannequin_Small`

![Image](https://github.com/user-attachments/assets/1b892828-e9f5-4ec8-a36d-f70a2a40157b)

**Comment by chompDev** [comment]
Fixed with: https://github.com/sp-tarkov/server/commit/8e255d86cb263245c7f81ffc32a5b4b087060c89

**Comment by Th3NightHawk** [comment]
Would I need to test the fix out on a new profile? Still getting the errors in the latest build:

```
[Client Request] /files/Hideout/EfT_UI_Icons_DogTag.png
File not found: /files/Hideout/EfT_UI_Icons_DogTag
[Client Request] /files/Hideout/EfT_UI_Icons_SmallTrophy.png
File not found: /files/Hideout/EfT_UI_Icons_SmallTrophy
[Client Request] /files/Hideout/EfT_UI_Icons_BigTrophy.png
File not found: /files/Hideout/EfT_UI_Icons_BigTrophy
[Client Request] /client/game/profile/items/moving
event: HideoutUpgrade
[Client Request] /files/Hideout/EfT_UI_Icons_DogTag.png
File not found: /files/Hideout/EfT_UI_Icons_DogTag
[Client Request] /files/Hideout/EfT_UI_Icons_SmallTrophy.png
File not found: /files/Hideout/EfT_UI_Icons_SmallTrophy
[Client Request] /files/Hideout/EfT_UI_Icons_BigTrophy.png
File not found: /files/Hideout/EfT_UI_Icons_BigTrophy
```

**Comment by Th3NightHawk** [comment]
Issue fixed with https://github.com/sp-tarkov/server/commit/9fcac4029e6148c84229608eec4151daacbd6dc5

![Image](https://github.com/user-attachments/assets/fe4ab3de-b684-4787-a336-bfcdf469d8f3)
